name: Delhi
favicon: null
layout_spectrum: 0.005964715499430895
typography_spectrum: 0.4663605270907283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.37093547941185534
  lightness: 0.922335600014776
  saturation: 0.7617682905402035
  rhythmicContrast: 0.8681632184889168
purpose: []
